dofile(TESTS .. "harness.lua")
local a = MakeClient("Fresh", {"!!!TwichUI"})
a.LOADED["!!!TwichUI"]=true; a.FireEvent("ADDON_LOADED","!!!TwichUI")
assert(a.TwichUIDB.modules.groupCheck == true, "on for new installs")
local b = MakeClient("Upgrader", {"!!!TwichUI"})
b.TwichUIDB = {modules = {groupCheck = false, shareGroup = true}}
b.LOADED["!!!TwichUI"]=true; b.FireEvent("ADDON_LOADED","!!!TwichUI")
assert(b.TwichUIDB.modules.groupCheck == false, "a saved choice is kept")
assert(b.TwichUIDB.modules.shareGroup == true, "other choices kept")
print("DEFAULTS TESTS PASSED")
