-- TwichUI: builds modules/TrainingData.lua from What's Training?'s WoW: Forever data.
-- Usage (from the repository root, with What's Training? checked out beside it):
--   lua5.1 tools/training_data.lua ../WhatsTraining > modules/TrainingData.lua
-- tools/update_training_data.sh does this from the newest upstream commit, then validates the result.
-- Reads only Classes/Camelot (the data What's Training? loads on Forever) and keeps what the
-- level-up training notice needs: spell IDs, the level each becomes trainable, prerequisite
-- spells, a required talent, faction and race limits, and the rank groups whose later ranks
-- replace earlier ones. Costs, pet abilities, warlock tomes and weapon skills are left out.
-- What's Training? is MIT licensed; its notice is in licenses/MIT-whatstraining.txt.

local source = arg[1] or "../WhatsTraining"
local CLASSES = { "DRUID", "HUNTER", "MAGE", "PALADIN", "PRIEST", "ROGUE", "SHAMAN", "WARLOCK", "WARRIOR" }

local function Title(class) return class:sub(1, 1) .. class:sub(2):lower() end

-- WT_SOURCE_VERSION (set by tools/update_training_data.sh) names the upstream commit; a git checkout's
-- .toc only carries the packager's "@project-version@" placeholder.
local function Version()
    local named = os.getenv("WT_SOURCE_VERSION")
    if named and named ~= "" then return named end
    local toc = assert(io.open(source .. "/WhatsTraining.toc"), "no WhatsTraining.toc in " .. source)
    local text = toc:read("*a")
    toc:close()
    return text:match("## Version:%s*([^\r\n]+)") or "unknown"
end

-- Runs one of What's Training?'s class files with a stand-in for its addon table.
local function Load(file, wt)
    local chunk = assert(loadfile(source .. "/Classes/Camelot/" .. file))
    chunk("WhatsTraining", wt)
end

local function Read(class)
    local wt = { currentClass = class }
    function wt.FactionFilter(t) return t end   -- keep every faction and race; the notice filters in game
    function wt.RaceFilter(t) return t end
    function wt:AddOverriddenSpells(...) self.ranks = { ... } end
    Load(Title(class) .. ".lua", wt)
    if class == "HUNTER" then Load("HunterPets.lua", wt) end
    assert(type(wt.SpellsByLevel) == "table", "no SpellsByLevel for " .. class)
    return wt
end

local function List(t)
    local parts = {}
    for i, v in ipairs(t) do parts[i] = tostring(v) end
    return "{ " .. table.concat(parts, ", ") .. " }"
end

local function Entry(spell)
    assert(type(spell.id) == "number", "spell without an id")
    local out = { tostring(spell.id) }
    if spell.requiredIds then out[#out + 1] = "req = " .. List(spell.requiredIds) end
    if spell.requiredTalentId then out[#out + 1] = "talent = " .. spell.requiredTalentId end
    if spell.faction then
        assert(spell.faction == "Alliance" or spell.faction == "Horde", "unknown faction " .. tostring(spell.faction))
        out[#out + 1] = ("faction = %q"):format(spell.faction)
    end
    local races = spell.races or (spell.race and { spell.race })
    if races then out[#out + 1] = "race = " .. List(races) end
    return "{ " .. table.concat(out, ", ") .. " }"
end

local out = {}
local function Put(line) out[#out + 1] = line end

Put("-- TwichUI: class training data for the level-up training notice (modules/Training.lua).")
Put("-- GENERATED by tools/training_data.lua; do not edit by hand. Regenerate it instead.")
Put(("-- Source: What's Training? %s by Sveng, Classes/Camelot (its WoW: Forever data)."):format(Version()))
Put("-- MIT licensed; see licenses/MIT-whatstraining.txt.")
Put("-- Each class is a function, so only the player's own class is ever built. It returns:")
Put("--   levels: [level] = { { spellID, req = { spellIDs }, talent = spellID, faction = \"Alliance\"|\"Horde\", race = { raceIDs } }, ... }")
Put("--   ranks:  { { spellIDs, lowest rank first }, ... } for abilities whose later ranks replace earlier ones")
Put("")
Put("local R = TwichUI")
Put("local D = {}")
Put("R.TrainingData = D")
Put("")
local total = 0
for _, class in ipairs(CLASSES) do
    local wt = Read(class)
    local pets = wt.PetAbilityIds or {}
    local levels = {}
    for level in pairs(wt.SpellsByLevel) do levels[#levels + 1] = level end
    table.sort(levels)
    Put(("D.%s = function()"):format(class))
    Put("    local levels = {")
    for _, level in ipairs(levels) do
        local entries = {}
        for _, spell in ipairs(wt.SpellsByLevel[level]) do
            if not pets[spell.id] then entries[#entries + 1] = Entry(spell) end
        end
        if #entries > 0 then
            total = total + #entries
            Put(("        [%d] = {"):format(level))
            for _, entry in ipairs(entries) do Put("            " .. entry .. ",") end
            Put("        },")
        end
    end
    Put("    }")
    Put("    local ranks = {")
    for _, group in ipairs(wt.ranks or {}) do Put("        " .. List(group) .. ",") end
    Put("    }")
    Put("    return levels, ranks")
    Put("end")
    Put("")
end
io.stderr:write(("%d entries written\n"):format(total))
io.write(table.concat(out, "\n"))
